version: 0.2
env:
  variables:
    S3_BUCKET: "rk0-site"
phases:
  install:
    commands:
        - echo Installing source NPM dependencies...
        - npm install
  build:
    commands:
        - echo Build started on `date`
        - npm run build
artifacts:
  files:
      - '**/*'
  base-directory: 'docs*'
  discard-paths: yes