version: 0.2
env:
  variables:
    S3_BUCKET: "rk0-site"
phases:
  install:
    commands:
        - echo Installing source NPM dependencies...
        - npm install
  build:
    commands:
        - echo Build started on `date`
        - npm run build
  post_build:
    commands:
      - aws s3 cp docs s3://${S3_BUCKET}/library-class --recursive
      - echo Build completed on `date`