AWSTemplateFormatVersion: 2010-09-09
Description: >
  Creates the ECS Cluster
Parameters:
  EnvironmentName:
    Type: String
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${EnvironmentName}-cluster"
Outputs:
  Cluster:
    Value: !Ref ECSCluster