AWSTemplateFormatVersion: 2010-09-09
Description: >
  Creates load balancers for the project
Parameters: 
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  VPC:
    Type: AWS::EC2::VPC::Id
  EnvironmentName:
    Type: String
    Description: "A prefix name for resources that need to be unique"
  Certificate:
    Type: String
    Description: "The cert fot the load balancer"
Resources: 
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      SecurityGroups: [ !Ref "SecurityGroup" ]
      Subnets: !Ref Subnets
      Type: "application"
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates: 
        - CertificateArn: !Ref Certificate
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup
  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-default0
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP
  LoadBalancerCert:
    Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    Properties:
      Certificates:
        - CertificateArn: !Ref Certificate
      ListenerArn: !Ref LoadBalancerListener
Outputs:
  LoadBalancer:
    Value: !Ref LoadBalancer
  Listener:
    Value: !Ref LoadBalancerListener
  DNSName:
    Value: !GetAtt LoadBalancer.DNSName