AWSTemplateFormatVersion: 2010-09-09
Resources:
  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 5
Outputs:
  LogGroup:
    Value: !Ref CloudWatchLogsGroup