AWSTemplateFormatVersion: 2010-09-09
Description: >
  Creates a CNAME for the load balancer
Parameters:
  HostedZone:
    Type: String
  ApiUrl:
    Type: String
  LoadBalancerUrl:
    Type: String
Resources:
  LoadBalancerCName:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZone
      Name: !Join ["", [!Ref ApiUrl, ".", !Ref "HostedZone"]]
      Type: CNAME
      ResourceRecords: 
        - !Ref LoadBalancerUrl
      TTL: "300"
Outputs:
  ApiUrl:
    Value: !Ref LoadBalancerCName