AWSTemplateFormatVersion: 2010-09-09
Description: >
  The security groups for this stack
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
Resources: 
  LoadBalancerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allows HTTP access to the load balancer"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          ToPort: 443
          IpProtocol: tcp
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Access to the ECS hosts and the tasks/containers that run on them
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref LoadBalancerSecGroup
          IpProtocol: "-1"
Outputs:
  LoadBalancerSecurityGroup:
    Value: !Ref LoadBalancerSecGroup
  ContainerSecurityGroup:
    Value: !Ref ContainerSecurityGroup