AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template describes the build pipeline
Parameters:
  PipelineName:
    Type: String
  SourceOAuth:
    Type: String
    NoEcho: true
  FrontendBucket:
    Type: String
  Cluster: 
    Type: String
  GameService: 
    Type: String
  Repository:
    Type: String
Resources:
  BuildProjects:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./build-projects.yml"
      Parameters:
        CodeBuildRole: !GetAtt Roles.Outputs.CodeBuildRole
        Repository: !Ref Repository
  Roles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./roles.yml"
      Parameters:
        ArtifactBucket: !GetAtt Storage.Outputs.ArtifactBucket
        FrontendBucket: !Ref FrontendBucket
  Storage:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./storage.yml"
      Parameters: 
        PipelineBucketName: !Sub ${PipelineName}-bucket
  Pipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./code-pipeline.yml"
      Parameters:
        PipelineRole: !GetAtt Roles.Outputs.CodePipelineRole
        PipelineName: !Ref PipelineName
        ArtifactBucket: !GetAtt Storage.Outputs.ArtifactBucket
        FrontendBuild: !GetAtt BuildProjects.Outputs.FrontendBuild
        BackendBuild: !GetAtt BuildProjects.Outputs.BackendBuild
        FrontendBucket: !Ref FrontendBucket
        Cluster: !Ref Cluster
        GameService: !Ref GameService
        SourceOAuth: !Ref SourceOAuth